

<div class="account-create testi">
    <div class="page-title">
        <h1><?php echo $this->__('testimonials Details'); ?></h1>
    </div>
    
        <div class="fieldset">
          
            <p class="form-instructions"><?php echo $this->__('Details of testimonials'); ?></p>
          
            <ul class="form-list">


          <?php 	
 					$id = $this->getRequest()->getParams('id');
					foreach (array_values($id) as $i => $value) 
					{
  				$value;
					}
					$value;		
  				$model = Mage::getModel('testimonials/testimonialss');
		      $collection = $model->getCollection()
		      ->addFieldToFilter('status', 1)
					->addFieldToFilter('id',$value);
		      $data = $collection->getData();
		      foreach($data as $row):
           ?>
        
            <li>
                <div  class="list-inner contenttestimonials">
                    <div>
                    <?php echo '<img class="img-responsive img-circle" width="70" src="' . Mage::getBaseUrl('media').'/'.$row["picture"] . '"/>';?>
										</div>
</br>                    
										<div>
										<p>
                       <?php echo $row["testimonials"]; ?>
										</p>
										</div>
										<div>
                     -<a href="#"><span class="testname">- <?php echo $row["customer_name"]; ?></span></a>

										</div>
                </div>   
                
            </li> 
           
            
            <?php endforeach; ?>
            
            
         
            </ul>


        </div>
      

        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>" class="back-link"><small>« </small><?php echo $this->__('Back'); ?></a></p>

        </div>
   
   



</div>
