
<div class="account-create testi">
    <div class="page-title">
        <h1><?php echo $this->__('Post Testimonial'); ?></h1>
    </div>
    <?php
    	if (Mage::getSingleton("customer/session")->isLoggedIn()):
    ?>
    <form  action="<?php echo $this->getUrl('testimonials/index/save'); ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
        <div class="fieldset">
	<?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="success_url" value="">
            <input type="hidden" name="error_url" value="">
            <p class="form-instructions"><?php echo $this->__('Please put data to post your testimonials.'); ?></p>
            <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
            <ul class="form-list">


            <?php
            $email="";
            $first="";
            $middle="";
            $last="";
            
            $customer = Mage::getSingleton("customer/session")->getCustomer();

            $email = $customer->getEmail();
            $first = $customer->getFirstname();
            $middle = $customer->getMiddlename();
            $last = $customer->getLastname(); 
            
            
        
            ?>

                <input type="hidden" id="status" name="status" value="1">
		<input type="hidden" id="user_id" name="user_id" value="<?php echo $customer->getId();?>">
                <li>
                    <label for="email_address" class="required"><em>*</em>

                        <?php echo $this->__('Customer Email Address'); ?>
                    </label>
                    <div class="input-box">
                        <input type="email" readonly = readonly value="<?php echo $email; ?>" autocapitalize="off" autocorrect="off" spellcheck="false" name="customer_email" id="email_address" value="" title="Email Address" class="input-text validate-email required-entry">
                    </div>
                </li>


                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label for="firstname" class="required"><em>*</em>
                                <?php echo $this->__('Customer Name'); ?>
                            </label>
                            <div class="input-box">
                                <input type="text" id="name" name="customer_name" readonly = readonly value="<?php echo $first; ?> <?php echo $last; ?>" title="Name" maxlength="255" class="input-text required-entry">
                            </div>
                        </div>

                    </div>
                </li>

                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label for="name" class="required"><em>*</em>
                                <?php echo $this->__('Testimonials'); ?></label>
                            <div class="input-box">
                            <textarea class="input-text required-entry" cols="10" name="testimonials" rows="3"></textarea>
                            </div>
                        </div>


                    </div>

                </li>
                


            </ul>


        </div>
        <div class="buttons-set">

            <button style="float:left;" type="submit" title="Submit" class="button"><span><span><?php echo $this->__('Submit'); ?>
            </span></span></button>
        </div>
	
	

        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->getUrl('testimonials/index/') ?>" class="back-link"><small>« </small><?php echo $this->__('Back to testimonials'); ?></a></p>

        </div>
    </form>
    <?php
	else:
	echo 'Please login or register new account';
	endif; 
    ?>

</div>
