<?php echo $this->getMessagesBlock()->getGroupedHtml();
$collection = $this->getCollection(); 

echo $this->getPagerHtml();
if($collection->getSize()):
?>
<table class="data-table">
    <colgroup>
        <col width="100px"/>
        <col/>
    </colgroup>
    
    <thead>
        <tr>
            <td colspan="2"> <h1 class="left"><?php echo $this->__('Customer Testimonials')?></h1></td>
        </tr>
    </thead>
    
    <tbody>
        <?php
	if(Mage::app()->getRequest()->getParam('p'))
        {
            $curr_page    =    Mage::app()->getRequest()->getParam('p');
        } else {
	    $curr_page    =    1;
	}
	if(Mage::app()->getRequest()->getParam('limit'))
        {
            $limit    =    Mage::app()->getRequest()->getParam('limit');
        } else {
	    $limit    =    10;
	}
        $model = Mage::getModel('testimonials/testimonialss');
        $collection = $model->getCollection()
	     ->setCurPage($curr_page) 
	     ->setPageSize($limit)
             ->addFieldToFilter('status', 1);
        $data = $collection->getData();
        foreach ($data as $row):
        ?>
            <tr>
                
                <td>
                    
                    <dl>
                        <dt><?php $string = $row["testimonials"]; ?></dt>
                        <dd><?php
                                $string = strip_tags($string);

                                if (strlen($string) > 175) {
                                    $stringCut = substr($string, 0, 175);
                                    $string = substr($stringCut, 0, strrpos($stringCut, ' ')) . '..<a class="read-more" href="' . $this->getUrl('testimonials/detail/index', array('id' => $row["id"])) . '">Read More</a>';
                                }
                                echo $string;
                                ?></dd>
                    </dl>
		    <?php $customer_data = Mage::getModel('customer/customer')->load($row['user_id']); 
		    ?>
                    <h4 class="right">Author - <?php echo $customer_data->getFirstname() . $customer_data->getLastname(); ?></h4>
                    
                    
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody> 
    
    <tfoot>
        <tr>
            <td colspan="2">

		<?php if (Mage::getSingleton("customer/session")->isLoggedIn()): ?>
                <button  class="button right"  title="<?php echo $this->__('Add testimonials') ?>" type="button" 
             	    onclick="setLocation('<?php echo $this->getUrl('testimonials/index/form'); ?>')">
                    <span><span><?php echo $this->__('Add testimonials') ?></span></span>
                </button>
		<?php endif;?>

	  	
            </td>
        </tr>
    </tfoot>    

</table>

<?php else:?>
<?php if (Mage::getSingleton("customer/session")->isLoggedIn()): ?>
<div>
                <button  class="button right"  title="<?php echo $this->__('Add testimonials') ?>" type="button" 
             	    onclick="setLocation('<?php echo $this->getUrl('testimonials/index/form'); ?>')">
                    <span><span><?php echo $this->__('Add testimonials') ?></span></span>
                </button>
</div>
<?php endif;?>
<?php endif; ?>
